import sys, re

def process_html():
    with open('seller-k-products.html', 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()
    
    # 1. Update IDs to match JS
    content = content.replace('id="kpiTotalItems"', 'id="skTotalCount"')
    content = content.replace('id="kpiTotalPurchase"', 'id="skTotalBuy"')
    content = content.replace('id="kpiTotalSales"', 'id="skTotalSell"')
    content = content.replace('id="kpiTotalProfit"', 'id="skTotalProfit"')
    content = content.replace('id="shippingQtyGroup"', 'id="shippingQtyWrap"')
    content = content.replace('id="skCommission"', 'id="skPreviewCommission"')
    content = content.replace('id="skProfit"', 'id="skPreviewProfit"')
    content = content.replace('id="skProfitRate"', 'id="skPreviewRate"')
    
    # 2. Fix the corrupted Korean (Mojibake)
    content = content.replace('<title>K&G ?€?촋 ??留ㅼ엯?곹뭹 由ъ뒪??/title>', '<title>K&G 셀러K 매입상품 리스트</title>')
    content = content.replace('<!-- 濡쒓렇???ㅻ쾭?덉씠 -->', '<!-- 로그인 오버레이 -->')
    content = content.replace('<p>?쒖뒪?쒖뿉 ?묎렐 沅뚰븳??꾩슂?⑸땲??</p>', '<p>시스템 접근 권한이 필요합니다.</p>')
    content = content.replace('<label for="loginEmail">?꾩씠??(?대찓??</label>', '<label for="loginEmail">아이디 (이메일)</label>')
    content = content.replace('<label for="loginPassword">鍮꾨?踰덊샇</label>', '<label for="loginPassword\">비밀번호</label>')
    content = content.replace('濡쒓렇??', '로그인')
    content = content.replace('?꾩씠??먮뒗 鍮꾨?踰덊샇媛€ ?€?렸?듬땲??', '아이디 또는 비밀번호가 틀렸습니다.')
    content = content.replace('<!-- 硫붿씤 ??-->', '<!-- 메인 앱 -->')
    content = content.replace('<div class="menu-label">硫붾돱</div>', '<div class="menu-label">메뉴</div>')
    content = content.replace('<span>?€?쒕낫??/span>', '<span>대시보드</span>')
    content = content.replace('<span>?낆텧怨??깅줉</span>', '<span>입출고 등록</span>')
    content = content.replace('<span>?ш퀬 紐⑸줉</span>', '<span>재고 목록</span>')
    content = content.replace('<span>?낆텧怨??댁뿭</span>', '<span>입출고 내역</span>')
    content = content.replace('<div class="menu-label">?€?촋 K</div>', '<div class="menu-label">셀러K</div>')
    content = content.replace('<span>?ㅻ쭏?몄뒪?좎뼱</span>', '<span>스마트스토어</span>')
    content = content.replace('<span>留ㅼ엯?곹뭹 由ъ뒪??/span>', '<span>매입상품 리스트</span>')
    content = content.replace('<span>濡쒓렇?먯썐</span>', '<span>로그아웃</span>')
    content = content.replace('<h1 class="page-title">留ㅼ엯?곹뭹 由ъ뒪??/h1>', '<h1 class="page-title">매입상품 리스트</h1>')
    content = content.replace('?좉퇋 留ㅼ엯?곹뭹', '신규 매입상품 추가')
    content = content.replace('?꾩껜 留ㅼ엯 嫄댁닔', '전체 매입 건수')
    content = content.replace('珥?留ㅼ엯 湲덉븸', '총 매입 금액')
    content = content.replace('珥?留ㅼ텧 湲덉븸', '총 매출 금액')
    content = content.replace('珥??뺤궛 湲덉븸', '총 정산 금액')
    content = content.replace('?좏깮 ???', '선택 삭제')
    content = content.replace('怨듦툒泥?', '공급처')
    content = content.replace('釉뚮옖??', '브랜드')
    content = content.replace('?곹뭹紐?', '상품명')
    content = content.replace('?됱긽', '색상')
    content = content.replace('?ъ씠??', '사이즈')
    content = content.replace('?낅줈?쇱씪??', '업로드일자')
    content = content.replace('<span>留ㅼ엯媛€</span>', '<span>매입가</span>')
    content = content.replace('<span>?€諛곕퉬</span>', '<span>택배비</span>')
    content = content.replace('<span>?댁엫湲곗?</span>', '<span>운임기준</span>')
    content = content.replace('<span>珥?湲덉븸</span>', '<span>총 금액</span>')
    content = content.replace('<span>?먮ℓ媛€</span>', '<span>판매가</span>')
    content = content.replace('<span>諛곗넚鍮?</span>', '<span>배송비</span>')
    content = content.replace('<span>?섏닔猷?</span>', '<span>수수료</span>')
    content = content.replace('<span>?뺤궛湲?</span>', '<span>정산금</span>')
    content = content.replace('<span>?댁씡瑜?</span>', '<span>이익률</span>')
    content = content.replace('愿€由?', '관리')
    content = content.replace('<!-- 留ㅼ엯?곹뭹 異붽?/?섏젙 紐⑤떖 -->', '<!-- 매입상품 추가/수정 모달 -->')
    content = content.replace('?좉퇋 留ㅼ엯?곹뭹 異붽?', '신규 매입상품 추가')
    content = content.replace('湲곕낯 ?뺣낫', '기본 정보')
    content = content.replace('?곹뭹 ?뺣낫', '상품 정보')
    content = content.replace('留ㅼ엯/?먮ℓ ?뺣낫', '매입/판매 정보')
    content = content.replace('?뺤궛 誘몃━蹂닿린', '정산 미리보기')
    content = content.replace('痍⑥냼', '취소')
    content = content.replace('??옣?섍린', '저장하기')
    content = content.replace('<option value="?섎웾蹂?">?섎웾蹂?</option>', '<option value="수량별">수량별</option>')
    content = content.replace('<option value="臾대즺">臾대즺</option>', '<option value="무료">무료</option>')
    content = content.replace('<option value="議곌굔遺?">議곌굔遺?</option>', '<option value="조건부">조건부</option>')
    content = content.replace('<option value="?좊즺">?좊즺</option>', '<option value="유료">유료</option>')
    content = content.replace('?곸슜 湲곗? ?섎웾', '적용 기준 수량')
    content = content.replace('留ㅼ엯 珥쒖븸 (VAT ?ы븿)', '매입 총액 (VAT 포함)')
    content = content.replace('留ㅼ텧 珥쒖븸 (VAT ?ы븿)', '매출 총액 (VAT 포함)')
    content = content.replace('?덉긽 留덉쭊', '예상 마진')
    content = content.replace('?덉긽 留덉쭊瑜?', '예상 마진율')
    content = content.replace('?덉긽 ?섏닔猷?', '예상 수수료')

    with open('seller-k-products.html', 'w', encoding='utf-8') as f:
        f.write(content)

process_html()
